#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Imposta la disposizione dei workspaces
bspc monitor -d 1 2 3 4 5

# Imposta il bordo delle finestre
bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color "#74c69d" # EC7570, 74c69d
bspc config normal_border_color  "#44475a"

bspc config split_ratio          0.5

# Avvia i processi necessari
picom &
killall dunst; dunst &
killall polybar; polybar &
feh --bg-fill ~/.config/wallpaper.jpg &

# Imposta il cursore del mouse come una freccia 
# piuttosto che una "X" quando si punta sullo sfondo
xsetroot -cursor_name left_ptr &


bspc config focus_follows_mouse true
bspc config focus_follows_pointer true